[build]
command = "bash scripts/netlify-build.sh"


[[headers]]
for = "/assets/*"
[headers.values]
Access-Control-Allow-Origin = "*" # Allow CORS for https://services.w3.org/htmldiff


[[plugins]]
package = "netlify-plugin-cache"
[plugins.inputs]
paths = ["fonts"]

[[plugins]]
package = "netlify-plugin-debug-cache"
